server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html index.htm;

  location /api {
    proxy_pass http://backend:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  # Optional: Add headers to prevent caching issues
  location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
    expires 1y;
    add_header Cache-Control "public";
  }
}
