import React, { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Shield, CheckCircle2 } from 'lucide-react';
import { Header } from '@/components/Header';

const DashboardPage: React.FC = () => {
  const navigate = useNavigate();

  useEffect(() => {
    const token = localStorage.getItem('fakecheck_token');
    if (!token) {
      navigate('/resend');
    }
  }, [navigate]);

  const handleLogout = () => {
    localStorage.removeItem('fakecheck_token');
    localStorage.removeItem('fakecheck_email');
    navigate('/');
  };

  const token = localStorage.getItem('fakecheck_token');
  const email = localStorage.getItem('fakecheck_email');

  if (!token) {
    return null; // Will redirect
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-teal-50 dark:from-slate-900 dark:to-slate-800">
      <Header />
      <div className="flex items-center justify-center p-4 pt-20">
        <div className="w-full max-w-2xl">
          <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-xl p-8 border border-border">
            {/* Success Icon */}
            <div className="flex flex-col items-center mb-8">
              <div className="w-20 h-20 bg-gradient-to-br from-green-500 to-teal-500 rounded-full flex items-center justify-center mb-4 animate-bounce">
                <CheckCircle2 className="w-10 h-10 text-white" />
              </div>
              <h1 className="text-3xl font-bold text-foreground text-center">
                Email Verified!
              </h1>
              <p className="text-muted-foreground text-center mt-2">
                Your account has been successfully verified
              </p>
            </div>

            {/* Dashboard Content */}
            <div className="space-y-4 mb-8">
              <div className="p-6 bg-gradient-to-r from-primary/10 to-secondary/10 dark:from-primary/20 dark:to-secondary/20 rounded-lg border-2 border-primary/20">
                <div className="flex items-start gap-4">
                  <Shield className="w-6 h-6 text-primary flex-shrink-0 mt-1" />
                  <div>
                    <h3 className="font-semibold text-foreground mb-2">
                      Welcome to VerifySphere
                    </h3>
                    <p className="text-sm text-muted-foreground mb-3">
                      You can now access all features of VerifySphere, including AI-powered news verification, 
                      source credibility analysis, and community-driven fact-checking.
                    </p>
                    {email && (
                      <p className="text-xs text-muted-foreground">
                        Verified email: <span className="font-medium text-foreground">{email}</span>
                      </p>
                    )}
                  </div>
                </div>
              </div>

              {/* Token Display */}
              <div className="p-4 bg-muted rounded-lg border border-border">
                <p className="text-xs font-medium text-foreground mb-2">Demo Token:</p>
                <p className="text-xs font-mono text-muted-foreground break-all">{token}</p>
                <p className="text-xs text-muted-foreground mt-2">
                  This is a demo token generated by the mock OTP service. In production, this would be a real JWT token.
                </p>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex gap-4">
              <button
                onClick={handleLogout}
                className="flex-1 px-6 py-3 border-2 border-input bg-background text-foreground rounded-lg font-semibold hover:bg-accent transition-all"
              >
                Sign Out
              </button>
              <button
                onClick={() => navigate('/')}
                className="flex-1 px-6 py-3 bg-gradient-to-r from-primary to-secondary text-primary-foreground rounded-lg font-semibold hover:opacity-90 transition-all"
              >
                Go to Home
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DashboardPage;
